
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Dec 12 20:00:00 CST 2020
//----------------------------------------------------

package com.palmartec.analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_booleano = 7;
  public static final int ERROR = 12;
  public static final int EOF = 0;
  public static final int Apertura = 4;
  public static final int P_coma = 6;
  public static final int Value = 11;
  public static final int Cierre = 5;
  public static final int Identificador = 8;
  public static final int error = 1;
  public static final int Flotante = 10;
  public static final int Igual = 3;
  public static final int Numero = 9;
  public static final int Comillas = 2;
}

